version: '3.8'

services:
  postgres:
    image: postgres:16-alpine
    container_name: crypto_postgres
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
      POSTGRES_DB: crypto_wallet
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  mongodb:
    image: mongo:7-jammy
    container_name: crypto_mongodb
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db

  redis:
    image: redis:7-alpine
    container_name: crypto_redis
    ports:
      - "6379:6379"

  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: crypto_rabbitmq
    environment:
      RABBITMQ_DEFAULT_USER: admin
      RABBITMQ_DEFAULT_PASS: password
    ports:
      - "15672:15672" # Админка RabbitMQ
      - "5672:5672"

  rest_api:
    build:
      context: .
      dockerfile: backend/rest_api/deploy/server/Dockerfile
    container_name: crypto_api
    ports:
      - "8000:8000"
    env_file:
      - backend/rest_api/.env
    depends_on:
      - postgres
      - mongodb
      - redis
      - rabbitmq
    volumes:
      - .:/app

  ethereum_service:
    build:
      context: .
      dockerfile: backend/ethereum/deploy/server/Dockerfile
    container_name: crypto_ethereum_worker
    ports:
      - "8002:8002"
    env_file:
      - backend/ethereum/.env
    depends_on:
      - rabbitmq
      - redis
    volumes:
      - .:/app

  sockets_service:
    build:
      context: .
      dockerfile: backend/sockets/deploy/server/Dockerfile
    container_name: crypto_sockets
    ports:
      - "8004:8004"
    env_file:
      - backend/sockets/.env
    depends_on:
      - rabbitmq
      - redis
    volumes:
      - .:/app

  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    container_name: crypto_nginx
    ports:
      - "80:80"
    depends_on:
      - rest_api
      - sockets_service

volumes:
  postgres_data:
  mongodb_data:
