version: '3.8'

services:
  postgres:
    image: postgres:16-alpine
    container_name: crypto_postgres
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
      POSTGRES_DB: crypto_wallet
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:7-alpine
    container_name: crypto_redis

  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: crypto_rabbitmq
    environment:
      RABBITMQ_DEFAULT_USER: admin
      RABBITMQ_DEFAULT_PASS: password
    ports:
      - "15672:15672" # Админка RabbitMQ

  rest_api:
    build:
      context: .
      dockerfile: backend/rest_api/deploy/server/Dockerfile
    container_name: crypto_api
    env_file:
      - backend/rest_api/.env
    depends_on:
      - postgres
      - redis
      - rabbitmq

  rest_worker:
    build:
      context: .
      dockerfile: backend/rest_api/deploy/worker/Dockerfile
    container_name: crypto_worker
    env_file:
      - backend/rest_api/.env
    depends_on:
      - rabbitmq

  ethereum_api:
    build:
      context: .
      dockerfile: backend/ethereum/deploy/server/Dockerfile
    container_name: crypto_ethereum_api
    env_file:
      - backend/ethereum/.env
    depends_on:
      - postgres
      - redis
      - rabbitmq

  ethereum_worker:
    build:
      context: .
      dockerfile: backend/ethereum/deploy/worker/Dockerfile
    container_name: crypto_ethereum_worker
    env_file:
      - backend/ethereum/.env
    depends_on:
      - rabbitmq

  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    container_name: crypto_nginx
    ports:
      - "80:80"
    depends_on:
      - rest_api
      - ethereum_api

volumes:
  postgres_data:
