# nginx/nginx.conf

events {
    worker_connections 1024;
}

http {
    # Перенаправляем запросы к микросервису Ethereum
    upstream ethereum_service {
        server ethereum_api:8002;
    }

    # Перенаправляем остальные запросы к основному REST API (там же HTML/JS)
    upstream rest_api_service {
        server api:8000;
    }

    server {
        listen 80;

        # Маршруты для Ethereum-микросервиса
        location /api/v1/assets {
            proxy_pass http://ethereum_service;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }

        location /api/v1/wallets {
            proxy_pass http://ethereum_service;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }

        location /api/v1/faucet {
            proxy_pass http://ethereum_service;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }

        location /api/v1/transactions {
            proxy_pass http://ethereum_service;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }

        # Все остальные запросы (HTML, статика, авторизация, профиль) летят в основной API
        location / {
            proxy_pass http://rest_api_service;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }
    }
}
