"""add_ibay_models

Revision ID: 2b97eba35a07
Revises: 276295a3fa62
Create Date: 2026-04-12 12:35:24.909969

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2b97eba35a07'
down_revision: Union[str, Sequence[str], None] = '276295a3fa62'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ibay_products',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('wallet_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('price_eth', sa.Numeric(precision=36, scale=18), nullable=False),
    sa.Column('photo_url', sa.String(length=1024), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('ibay_products_user_id_fkey')),
    sa.ForeignKeyConstraint(['wallet_id'], ['wallets.id'], name=op.f('ibay_products_wallet_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('ibay_products_pkey'))
    )
    op.create_table('ibay_orders',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('product_id', sa.Uuid(), nullable=False),
    sa.Column('buyer_user_id', sa.UUID(), nullable=False),
    sa.Column('tx_hash', sa.String(length=100), nullable=False),
    sa.Column('price_eth', sa.Numeric(precision=36, scale=18), nullable=False),
    sa.Column('status', sa.Enum('NEW', 'DELIVERY', 'COMPLETED', 'FAILED', 'RETURNED', name='orderstatus'), nullable=False),
    sa.Column('return_tx_hash', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['buyer_user_id'], ['users.id'], name=op.f('ibay_orders_buyer_user_id_fkey')),
    sa.ForeignKeyConstraint(['product_id'], ['ibay_products.id'], name=op.f('ibay_orders_product_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('ibay_orders_pkey'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('ibay_orders')
    op.drop_table('ibay_products')
    # ### end Alembic commands ###
