"""initial_ethereum_tables

Revision ID: c5ebdee864f5
Revises: 
Create Date: 2026-03-27 13:05:18.387492

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c5ebdee864f5'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('assets',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('ticker', sa.String(length=10), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('network', sa.String(length=50), nullable=False),
    sa.Column('asset_type', sa.String(length=20), nullable=False),
    sa.Column('decimals', sa.Integer(), nullable=False),
    sa.Column('contract_address', sa.String(length=42), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('assets_pkey'))
    )
    op.create_index(op.f('assets_ticker_idx'), 'assets', ['ticker'], unique=False)
    op.create_table('wallets',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('asset_id', sa.UUID(), nullable=False),
    sa.Column('address', sa.String(length=42), nullable=False),
    sa.Column('private_key_encrypted', sa.String(), nullable=False),
    sa.Column('balance', sa.Numeric(), nullable=False),
    sa.Column('balance_updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['asset_id'], ['assets.id'], name=op.f('wallets_asset_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('wallets_pkey')),
    sa.UniqueConstraint('user_id', 'asset_id', name='uq_wallet_user_asset')
    )
    op.create_index(op.f('wallets_address_idx'), 'wallets', ['address'], unique=False)
    op.create_index(op.f('wallets_user_id_idx'), 'wallets', ['user_id'], unique=False)
    op.create_table('transactions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('wallet_id', sa.UUID(), nullable=False),
    sa.Column('tx_hash', sa.String(length=66), nullable=False),
    sa.Column('from_address', sa.String(length=42), nullable=False),
    sa.Column('to_address', sa.String(length=42), nullable=False),
    sa.Column('value', sa.Numeric(), nullable=False),
    sa.Column('tx_fee', sa.Numeric(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['wallet_id'], ['wallets.id'], name=op.f('transactions_wallet_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('transactions_pkey'))
    )
    op.create_index(op.f('transactions_from_address_idx'), 'transactions', ['from_address'], unique=False)
    op.create_index(op.f('transactions_status_idx'), 'transactions', ['status'], unique=False)
    op.create_index(op.f('transactions_to_address_idx'), 'transactions', ['to_address'], unique=False)
    op.create_index(op.f('transactions_tx_hash_idx'), 'transactions', ['tx_hash'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('transactions_tx_hash_idx'), table_name='transactions')
    op.drop_index(op.f('transactions_to_address_idx'), table_name='transactions')
    op.drop_index(op.f('transactions_status_idx'), table_name='transactions')
    op.drop_index(op.f('transactions_from_address_idx'), table_name='transactions')
    op.drop_table('transactions')
    op.drop_index(op.f('wallets_user_id_idx'), table_name='wallets')
    op.drop_index(op.f('wallets_address_idx'), table_name='wallets')
    op.drop_table('wallets')
    op.drop_index(op.f('assets_ticker_idx'), table_name='assets')
    op.drop_table('assets')
    # ### end Alembic commands ###
