"""remove_wallet_unique_constraint

Revision ID: f8a2a9554a53
Revises: c5ebdee864f5
Create Date: 2026-04-01 12:55:13.190666

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f8a2a9554a53'
down_revision: Union[str, Sequence[str], None] = 'c5ebdee864f5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('uq_wallet_user_asset'), 'wallets', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(op.f('uq_wallet_user_asset'), 'wallets', ['user_id', 'asset_id'], postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###
